branch-defaults:
  master:
    environment: covid19server-dev
global:
  application_name: covid19server
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 (BETA)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/covid19server-eb.jar
